// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Api$BsDiscord = require("./Api.bs.js");
var Constants$BsDiscord = require("../Constants.bs.js");
var PayloadParser$BsDiscord = require("../PayloadParser.bs.js");

function createMessage(channelId, content) {
  var body = { };
  body["content"] = content;
  return fetch(Constants$BsDiscord.apiBaseUrl + ("/channels/" + (String(channelId) + "/messages")), Fetch.RequestInit[/* make */0](/* Post */2, {
                          "Content-Type": "application/json",
                          Authorization: "Bot " + (String(Constants$BsDiscord.token) + "")
                        }, Caml_option.some(JSON.stringify(body)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (response) {
                    var statusCode = response.status;
                    var switcher = statusCode - 200 | 0;
                    if (switcher > 4 || switcher < 0) {
                      if (switcher !== 104) {
                        return Promise.reject([
                                    Api$BsDiscord.ApiError,
                                    statusCode
                                  ]);
                      } else {
                        return Promise.resolve(response);
                      }
                    } else if (switcher === 3 || switcher === 2) {
                      return Promise.reject([
                                  Api$BsDiscord.ApiError,
                                  statusCode
                                ]);
                    } else {
                      return Promise.resolve(response);
                    }
                  })).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                var message = PayloadParser$BsDiscord.message(json);
                console.log("createMessage", message);
                return Promise.resolve(message);
              }));
}

function createParams(params) {
  var filteredParams = /* array */[];
  List.iter((function (param) {
          var value = param[1];
          if (value !== undefined) {
            filteredParams.push(/* tuple */[
                  param[0],
                  value
                ]);
            return /* () */0;
          } else {
            return /* () */0;
          }
        }), params);
  return filteredParams;
}

function getMessages(channelId, around, before, after, limit, param) {
  return Api$BsDiscord.requestGet("/channels/" + (String(channelId) + "/messages"), createParams(/* :: */[
                    /* tuple */[
                      "around",
                      around
                    ],
                    /* :: */[
                      /* tuple */[
                        "before",
                        before
                      ],
                      /* :: */[
                        /* tuple */[
                          "after",
                          after
                        ],
                        /* :: */[
                          /* tuple */[
                            "limit",
                            Belt_Option.map(limit, (function (prim) {
                                    return String(prim);
                                  }))
                          ],
                          /* [] */0
                        ]
                      ]
                    ]
                  ]), /* () */0).then((function (json) {
                return Promise.resolve(Json_decode.array(PayloadParser$BsDiscord.message, json));
              }));
}

exports.createMessage = createMessage;
exports.createParams = createParams;
exports.getMessages = getMessages;
/* No side effect */
