// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Api$BsDiscord = require("./Api.bs.js");
var PayloadParser$BsDiscord = require("../PayloadParser.bs.js");

function getGuildEmojis(guildId) {
  return Api$BsDiscord.requestGet("/guilds/" + (String(guildId) + "/emojis"), undefined, /* () */0).then((function (json) {
                return Promise.resolve(Json_decode.array(PayloadParser$BsDiscord.emoji, json));
              }));
}

function getGuildEmoji(guildId, emojiId) {
  return Api$BsDiscord.requestGet("/guilds/" + (String(guildId) + ("/emojis/" + (String(emojiId) + ""))), undefined, /* () */0).then((function (json) {
                return Promise.resolve(PayloadParser$BsDiscord.emoji(json));
              }));
}

exports.getGuildEmojis = getGuildEmojis;
exports.getGuildEmoji = getGuildEmoji;
/* No side effect */
