// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Api$BsDiscord = require("./Api.bs.js");
var PayloadParser$BsDiscord = require("../PayloadParser.bs.js");

function getCurrentUser(param) {
  return Api$BsDiscord.requestGet("/users/@me", undefined, /* () */0).then((function (json) {
                return Promise.resolve(PayloadParser$BsDiscord.user(json));
              }));
}

function getUser(userId) {
  return Api$BsDiscord.requestGet("/users/" + (String(userId) + ""), undefined, /* () */0).then((function (json) {
                return Promise.resolve(PayloadParser$BsDiscord.user(json));
              }));
}

function updateCurrentUser(username, param) {
  var tmp = { };
  if (username !== undefined) {
    tmp.username = Caml_option.valFromOption(username);
  }
  var bodyJson = tmp;
  return Api$BsDiscord.requestPatch("/users/@me", Caml_option.some(bodyJson), /* () */0).then((function (json) {
                return Promise.resolve(PayloadParser$BsDiscord.user(json));
              }));
}

exports.getCurrentUser = getCurrentUser;
exports.getUser = getUser;
exports.updateCurrentUser = updateCurrentUser;
/* No side effect */
