// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Gateway$BsDiscord = require("./Gateway.bs.js");
var Constants$BsDiscord = require("./Constants.bs.js");
var ChannelApi$BsDiscord = require("./api/ChannelApi.bs.js");

((require('isomorphic-fetch')));

function onOpen(e) {
  console.log("onOpen", e);
  return /* () */0;
}

function onMessage(message) {
  console.log("onMessage", message);
  if (typeof message === "number" || message.tag !== 1) {
    return /* () */0;
  } else {
    var match = message[0];
    if (typeof match === "number" || match.tag !== 2) {
      return /* () */0;
    } else {
      var message$1 = match[0];
      if ("ping".indexOf(message$1[/* content */4]) !== -1) {
        ChannelApi$BsDiscord.createMessage(message$1[/* channelId */1], "pong");
        return /* () */0;
      } else {
        return 0;
      }
    }
  }
}

function onError(e) {
  console.log("onError", e);
  return /* () */0;
}

function onClose(e) {
  console.log("onClose", e);
  return /* () */0;
}

Gateway$BsDiscord.createSocket(Constants$BsDiscord.token, onOpen, onMessage, onError, onClose, /* () */0);

exports.onOpen = onOpen;
exports.onMessage = onMessage;
exports.onError = onError;
exports.onClose = onClose;
/*  Not a pure module */
