// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var apiBaseUrl = "https://discordapp.com/api/v6";

var token = "Mzk4OTE3OTQzNTc0MTM0Nzk1.XRKUnA.KNRkoqpdhZVMEvD3ti0abVECf-k";

exports.apiBaseUrl = apiBaseUrl;
exports.token = token;
/* No side effect */
