// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var WebsocketClient$BsDiscord = require("./WebsocketClient.bs.js");

var ws = WebsocketClient$BsDiscord.Websocket[/* make */2](undefined, "wss://gateway.discord.gg/?v=6&encoding=json");

WebsocketClient$BsDiscord.Websocket[/* onOpen */4](ws, (function (param) {
        console.log("onOpen");
        return /* () */0;
      }));

WebsocketClient$BsDiscord.Websocket[/* onMessage */7](ws, (function (ev) {
        console.log("onMessage", ev);
        return /* () */0;
      }));

WebsocketClient$BsDiscord.Websocket[/* onError */5](ws, (function (ev) {
        console.log("onError: " + (String(ev) + ""));
        return WebsocketClient$BsDiscord.Websocket[/* close */3](undefined, undefined, ws);
      }));

WebsocketClient$BsDiscord.Websocket[/* onClose */6](ws, (function (ev) {
        console.log("onClose: " + (String(ev) + ""));
        return /* () */0;
      }));

exports.ws = ws;
/* ws Not a pure module */
