// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  0,
  1,
  2,
  3,
  4,
  6,
  7,
  8,
  9,
  10,
  11
];

function opCodeToJs(param) {
  return Js_mapperRt.toInt(param, jsMapperConstantArray);
}

function opCodeFromJs(param) {
  return Js_mapperRt.fromInt(11, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -102231997,
    "READY"
  ],
  /* tuple */[
    889912559,
    "GUILD_CREATE"
  ],
  /* tuple */[
    975859715,
    "MESSAGE_CREATE"
  ]
];

function dispatchMessageTypeToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray$1);
}

function dispatchMessageTypeFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray$1, param);
}

exports.opCodeToJs = opCodeToJs;
exports.opCodeFromJs = opCodeFromJs;
exports.dispatchMessageTypeToJs = dispatchMessageTypeToJs;
exports.dispatchMessageTypeFromJs = dispatchMessageTypeFromJs;
/* No side effect */
