// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function messageTypeToJs(param) {
  return param + 0 | 0;
}

function messageTypeFromJs(param) {
  if (param <= 11 && 0 <= param) {
    return param - 0 | 0;
  }
  
}

exports.messageTypeToJs = messageTypeToJs;
exports.messageTypeFromJs = messageTypeFromJs;
/* No side effect */
