// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

function activityTypeToJs(param) {
  return param + 0 | 0;
}

function activityTypeFromJs(param) {
  if (param <= 2 && 0 <= param) {
    return param - 0 | 0;
  }
  
}

var jsMapperConstantArray = /* array */[
  /* tuple */[
    3406202,
    "dnd"
  ],
  /* tuple */[
    814535476,
    "idle"
  ],
  /* tuple */[
    871917747,
    "online"
  ]
];

function clientStatusTypeToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray);
}

function clientStatusTypeFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray, param);
}

function messageTypeToJs(param) {
  return param + 0 | 0;
}

function messageTypeFromJs(param) {
  if (param <= 11 && 0 <= param) {
    return param - 0 | 0;
  }
  
}

exports.activityTypeToJs = activityTypeToJs;
exports.activityTypeFromJs = activityTypeFromJs;
exports.clientStatusTypeToJs = clientStatusTypeToJs;
exports.clientStatusTypeFromJs = clientStatusTypeFromJs;
exports.messageTypeToJs = messageTypeToJs;
exports.messageTypeFromJs = messageTypeFromJs;
/* No side effect */
